// backend/src/data/mockEmails.ts
import { EmailDocument, DEFAULT_CATEGORY } from "../models/email.model";

export const mockEmails: EmailDocument[] = [
  {
    id: "1",
    accountId: "mock@gmail.com",
    folder: "INBOX",
    subject: "Welcome to ReachInbox!",
    body: "This is a demo email for testing purposes.",
    from: "noreply@reachinbox.com",
    to: ["user@gmail.com"],
    date: new Date(),
    aiCategory: DEFAULT_CATEGORY,
    indexedAt: new Date(),
  },
  {
    id: "2",
    accountId: "mock@gmail.com",
    folder: "INBOX",
    subject: "Project Work Update",
    body: "Please find attached the latest project report.",
    from: "manager@work.com",
    to: ["user@gmail.com"],
    date: new Date(),
    aiCategory: "Work",
    indexedAt: new Date(),
  },
  {
    id: "3",
    accountId: "mock@gmail.com",
    folder: "INBOX",
    subject: "Friend Reunion",
    body: "Hey! Let's catch up this weekend at our favorite cafe.",
    from: "friend@gmail.com",
    to: ["user@gmail.com"],
    date: new Date(),
    aiCategory: "General",
    indexedAt: new Date(),
  },
  {
    id: "4",
    accountId: "mock@gmail.com",
    folder: "INBOX",
    subject: "Big Sale on Electronics",
    body: "Don't miss our 50% off sale starting tomorrow!",
    from: "promotions@shop.com",
    to: ["user@gmail.com"],
    date: new Date(),
    aiCategory: "Spam",
    indexedAt: new Date(),
  },
  {
    id: "5",
    accountId: "mock@gmail.com",
    folder: "INBOX",
    subject: "Team Meeting Reminder",
    body: "Reminder: Our weekly sync-up meeting is scheduled for tomorrow at 10 AM.",
    from: "teamlead@work.com",
    to: ["user@gmail.com"],
    date: new Date(),
    aiCategory: "Meeting Booked",
    indexedAt: new Date(),
  },
  {
    id: "6",
    accountId: "mock@gmail.com",
    folder: "INBOX",
    subject: "Birthday Wishes!",
    body: "Happy Birthday! Wishing you a wonderful year ahead.",
    from: "family@gmail.com",
    to: ["user@gmail.com"],
    date: new Date(),
    aiCategory: "General",
    indexedAt: new Date(),
  },
  {
    id: "7",
    accountId: "mock@gmail.com",
    folder: "INBOX",
    subject: "Weekly Newsletter",
    body: "Here is your weekly newsletter with the latest updates.",
    from: "newsletter@service.com",
    to: ["user@gmail.com"],
    date: new Date(),
    aiCategory: "Not Interested",
    indexedAt: new Date(),
  },
  {
    id: "8",
    accountId: "mock@gmail.com",
    folder: "INBOX",
    subject: "System Maintenance Notice",
    body: "Our system will be down for maintenance tonight from 12 AM to 2 AM.",
    from: "support@company.com",
    to: ["user@gmail.com"],
    date: new Date(),
    aiCategory: "Out of Office",
    indexedAt: new Date(),
  },
  {
    id: "9",
    accountId: "mock@gmail.com",
    folder: "INBOX",
    subject: "Vacation Plans",
    body: "Let's finalize our travel itinerary for the upcoming vacation.",
    from: "friend2@gmail.com",
    to: ["user@gmail.com"],
    date: new Date(),
    aiCategory: "General",
    indexedAt: new Date(),
  },
  {
    id: "10",
    accountId: "mock@gmail.com",
    folder: "INBOX",
    subject: "Exclusive Offer Just for You",
    body: "Claim your exclusive 30% discount today only!",
    from: "deals@shopping.com",
    to: ["user@gmail.com"],
    date: new Date(),
    aiCategory: "Spam",
    indexedAt: new Date(),
  },
];
